nmfs-ost/ss3-doc

- .github/workflows/call-ss3-manual-html-release.yml
- 13output.tex
- 9control.tex
Added Info in documentation to address #140.
> add sex_ratio is by area to report:47

- docs/html_usermanual.css
- html_usermanual_snippets.html
resolves #156 
- updates navigation bar in html to be more clear
> Update html navbar

- 9control.tex
Resolves issue #162.
@kellijohnson-NOAA - I added you just to have a second reviewer to double check all the latex formatting looks good.
> update 2DAR section

- 9control.tex
- SS330_User_Manual.tex
> fix double normal selectivity section

- 9control.tex
Resolves #181 
PDF output: [SS330_User_Manual.pdf](https://github.com/nmfs-stock-synthesis/doc/files/12165402/SS330_User_Manual.pdf)
> add time-block description

- 9control.tex
Hi! This commit fixes a small typo in the Linf equation (Eq. 5).
> Fix typo in Linf equation

- 8data.tex
- _data_weighting.tex
Noticed this issue at the ICES course.
> Fix issue #189

- 6starter.tex
Fix alk section in response to stock-synthesis [PR #513](https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/513#pullrequestreview-1661868335)
> Fix ALK section to say it is disabled

- 8data.tex
> add changes issue #185

- 9control.tex
See issue [#535](https://github.com/nmfs-ost/ss3-source-code/issues/535) in ss3-source code.
@Rick-Methot-NOAA, I did not include the table because it seemed like adding it might confuse people more, but I'm happy to add in if you think otherwise.
> add info to Q bias adjust section about turning on float

- 9control.tex
See issue #180.
@iantaylor-NOAA can you take a look at my changes to the lambdas section and see if they make sense to you?
> Improve documentation of lambdas

- 8data.tex
> Cv to lognormal se correction

- 8data.tex
- SS330_User_Manual.tex
- docs/SS330_User_Manual_release.html
> Add guidance on implications of "addtocomp" values

- 6starter.tex
See PR [#589](https://github.com/nmfs-ost/ss3-source-code/pull/589) in ss3-source-code repo.
> Update multiyr average approach for depletion basis in starter

- .github/workflows/build-ss3-manual-pdf.yml
- 10optional_inputs.tex
- 12runningSS3.tex
- 6starter.tex
- 8data.tex
- 9control.tex
- dictionary.txt
See issue #108. 
Minor adjustment for table and then a myriad of other small formatting adjustments to fix tables and other minor issues in the pdf also.
> Formatting recr dist method table and tables in other files

- 13output.tex
- 9control.tex
- dictionary.txt
See issue #92.
- Fixed one hyperlink in output section too
- Also added link words to dictionary so they aren't flagged in that check of the github action
> Hyperlink selex patterns

- 15special.tex
- ss3_glossaries.tex
> Add text and link to Haikun's 2dar TMB code

- 13output.tex
@e-perl-NOAA, can you look over these small changes inspired by looking over #234 and reading through the new table.
Resolves #234.
> additional refinements to output table and associated text

- .github/workflows/add-artifact-to-pr.yml
Try to get the action working again
> try removing if push or pr statements from add artifact

- html_usermanual_snippets.html
Nav bar went to previous website, change to new website.
Change navbar to have table of contents be the first option.
> Fix nav bar to go to new website rather than previous one

- 8data.tex
- 9control.tex
> Fix wording for special survey type 35 for link type/index of dev vector

- 9control.tex
> Add text about lorenzen m morphs instead of platoons

- 8data.tex
- 9control.tex
Closes #290 
@Rick-Methot-NOAA Does this seem like a good place to add this text? I looked around the user manual but didn't really see anywhere else that it made sense to add it to.
> Add sentence about "hack" to do seasonal selectivity.

- .github/workflows/prerelease.yml
- 9control.tex
- SS330_User_Manual.tex
> Correct description of selectivity option 6 
