nmfs-ost/ss3-doc

- 9control.tex
relates to https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/86
This Pull Request does the following:
* documents the new spline input codes (10, 11, and 12)
* adds info on the previously undocumented "natural cubic spline" in ADMB
* a little more info is here: https://github.com/admb-project/admb/issues/180. 
* I tested fixing the slope parameters at 1e30 and it worked successfully although I don't yet have guidance on when it makes sense to use this feature.
* refines spline text in a few other places such as clarifying that it actually works OK to have the first node equal to the first bin, but not the last node equal to the last bin (I just checked)
* breaks the lines at ~80 characters to make it easier to track changes in long paragraphs that I was editing (I would …
> document new spline options, refine existing text

- 9control.tex
This addresses issue #114 survivorship-based Lorenzen M is now called via M case 6. Documentation is updated accordingly. This can be merged once SS issue #329 is accepted.
> Age-range based Lorenzen M as case 6

- 8data.tex
I followed the example data file and the information in data file reading in the [MV-Tweedie branch SS_write_ssnew file](https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/MV-Tweedie-ver2/SS_write_ssnew.tpl). The changes to the manual are rather minor but I am not sure if there are additional edits to describe this new option within SS3.
> Size frequency modifications to the manual detailing Dirichlet and MV Tweedie data fitting

- 8data.tex
I got a question from somebody confused by the sentence "The above data bins will combine 0-26 cm fish, >26 - 28 cm, ..., and 80+ cm fish" which references the vector 26 28 30 ... 80. I think that's not right. The 26cm bin includes both 0-26 and 26-28 fish. This pull request includes my attempt to clean up that section.
It took me 4 tries to get the tables to work, so we should use the option to squash the commits when merging.
**HTML rendering:** (is there a way to turn off the bold in the first row?)
**PDF rendering**:
> Length bins

- 9control.tex
This PR expands the example for "Controls for Variance of Derived Quantities" to use option 2 which includes more variables. This is based on a setup that I just used successfully for Petrale Sole.
It also fixes a few minor issues with the previous description. A screenshot of the example input looks in HTML in below (the PDF looks fine too).
It took 5 commits to make this simple change because I was trying and failing to shortcut to using \begin{quote}\begin{verbatim} instead, so we should squash the commits when merging to clean things up.
> improve example input for "Controls for Variance of Derived Quantities"

- 8data.tex
- SS330_User_Manual.tex
This pull request adds documentation for the newly added data weighting by partition option for length composition data ([stock-synthesis-pr#389](https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/389)) as described in issue #137. A table has been added with example data for option 2 in addition to the already existing example data table for option 1.
> Partition weighting

- .github/workflows/call-deploy-ss3-docs.yml
- docs/html_usermanual.css
Font changed in the html css file in the docs folder to be Arial, a sans-serif font as opposed to Georgia, a serif font. @kellijohnson-NOAA pointed out that there was a weird size difference in the numbers which turned out to just be a feature of the Georgia font, changing it to a font that doesn't have that size difference as a feature will get rid of that.
> change font in html from Georgia to Arial

- .github/workflows/build-ss3-manual-html.yml
- 1_4sections.tex
- 9control.tex
- SS.bib
- User_Guides/model_step_by_step/model_tutorial.Rmd
- User_Guides/ss_model_tips/ss_model_tips.Rmd
- technical_description/13biology.Rmd
- technical_description/_main.knit.md
- technical_description/_main.md
- technical_description/_main.tex
Hi! This pull request fixes minor typos:
- bootstap -> bootstrap
- the the -> the
- effects -> affects
- paramter -> parameter
- von Bert*y -> von Bertalanffy
- Joural -> Journal
- Volume and pages for Punt (2016) bib entry
All harmless, just cosmetic improvements.
> Fix minor typos

- 9control.tex
See stock-synthesis [issue #505](https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/505).
> A2 description fix

- 8data.tex
This change adds a note "Note: if retention is not defined in the selectivity section, observations with Partition = 2 will be changed to Partition = 0" to the two descriptions of partition (in the "Mean Body Weight or Length" and "Length Composition Data" sections) and also aligns the descriptions with each other a little bit.
Resolves #153.
> add note about retention required for part = 2

- 9control.tex
when working with age-specific selectivity of 1.0 for a range of ages.
Sorry if I made this pull request to the wrong base branch, i.e., it should not go into main. Feel free to suggest a different branch and I can rebase and submit a different/modified pull request.
The change in wording will be helpful to users that are new to selectivity type = 11. Even though I have used the type before I had to go to the Report.sso to make sure that it was doing what I thought it was. I was not sure if the parameters corresponded to the bins for ages or to the actual age numbers themselves. I also included an example in the suggested text.
> Suggested modifications for age-selectivity type 11

- .github/workflows/add-artifact-to-pr.yml
- 9control.tex
See ss3-source-code PR [#596](https://github.com/nmfs-ost/ss3-source-code/pull/596) and issue [#595](https://github.com/nmfs-ost/ss3-source-code/issues/595).
@Rick-Methot-NOAA Can you make sure the extra parameters table example looks okay?
@iantaylor-NOAA Could you take a look just to make sure it all makes sense?
> Update catchability section with env Q

- 15special.tex
- SS3.bib
- ss3_glossaries.tex
This PR inspired by an emailed question and follows discussion in closed PR #241.
Changes are:
- add note about lack of generalized software for tuning 2DAR selectivity
- remove paragraph about stand-alone TMB model for tuning the rho parameters
- align terminology by using "2DAR" throughout the User Manual instead of mix of "2DAR" and "2DAR1".
- update Xu et al. 2020 reference to final published year
@HaikunXu, please feel free to look over this revised text in the SS3 User Manual and suggest any changes. The existing text was from 2017 and caused some confusion about the available software for tuning the selectivity parameters.
I've added the "2024" milestone to r4ss issue https://github.com/r4ss/r4ss/issues/500 to improve the tools available in r4ss for tuning 2DAR selectivity and if …
> Revise text in tuning the 2DAR selectivity

- .github/workflows/build-ss3-manual-html.yml
Resolves issue pointed out in issue #60 of hard-coded number in html build workflow.
> Find max data-number instead of hard-coded number

- 15special.tex
- 9control.tex
Hi, this pull request fixes the following typos:
* and now there now is -> and now there is
* estimatable -> estimable
* kronecker -> Kronecker
> Fix typos: now, estimable, Kronecker

- 9control.tex
- dictionary.txt
Here's a draft pull request inspired by this recent conversation https://groups.google.com/g/ss3-forum/c/S-Krkkn9qao.
If an equation is necessary, we can likely do something similar to the description of the parameter trends which also use cumulative normal functions:
https://github.com/nmfs-ost/ss3-doc/blob/main/tv_parameter_description.tex#L81.
See issue #259
> improve description of hermaphroditism

- 7forecast.tex
- dictionary.txt
Max Cardinale noticed that the manual was unclear about how to add bycatch in the forecast file so the text inserted in the forecast section is added to clarify that. Additional links to appropriate sections have also been added.
> Add clarification about bycatch in forecast

- README.md
In the  README.md file, it looks better with the first occurrence of Stock Synthese as upper case with the acronym.
> Update README.md with upper case stock synthesis

- 9control.tex
This pull request improves the Schnute/Richards equations and the surrounding text.
The equations had significant errors, with Eq. 6 missing outer brackets and parts of Eq. 7 that should be subscripted or superscripted. There were also some inconsistencies in parameter names, such as Lmax/Linf/y2 that have been named L2.
> Improve Schnute/Richards equations

- 9control.tex
In light of the findings of Arni and Ian analyzing the Richards growth function in Stock Synthesis (draft [vignette](https://github.com/arni-magnusson/ss3-richards/blob/main/richards.pdf)) and a related question by Larry Jacobson on the Gompertz growth function (forum [message](https://groups.google.com/g/ss3-forum/c/dS-5KOnVjek?pli=1)), I would like to propose a revised text for the Richards growth function in the User Manual.
This pull request makes the following changes:
* Refer to "Richards" rather than "Schnute/Richards" growth function, to simplify and acknowledge that the Schnute parametrization (1981, Eq. 15) produces the same curves as other Richards parametrizations. Also to prevent confusion with the five-parameter Schnute-Richards (1990) growth function, which is quite …
> Revise section on Richards growth function

- SS330_User_Manual.tex
expl3 is part of the kernel and we don't need to pass all the options to it, you can probably delete this whole line but I just removed the portion that was leading to the problem. I haven't checked that the pdf looks the same.
close #282
> fix(expl3): Removes error checking
